### ISSUE TITLE
Missing indexes on foreign keys

### ISSUE THREAD

**Issue by nateberkopec** [codetriage/codetriage#1046]
A few tables are missing indexes on foreign keys

Grep schema.rb for _id and check for which ones are missing. There were a few when I checked.

**Comment by schneems** [comment]
Good catch. Would love it if there's some config that would force all foreign keys to have indexes and do that check in development.

**Comment by schneems** [comment]
Some gems are mentioned in these threads:

- https://twitter.com/schneems/status/1159482962238410752
- https://twitter.com/schneems/status/1159486933959094272

**Comment by anmolarora** [comment]
I will share the details for the missing indexes.

**Comment by anmolarora** [comment]
This table has all the indexes I could come up with by taking a look at the queries. Tried covering most of the DB queries.

|        Table       | Index to add                        | Index to remove      | Remarks                                                                  |
|:------------------:|-------------------------------------|----------------------|--------------------------------------------------------------------------|
| users              | github_access_token                 |                      | rake schedule:check_user_auth                                            |
| users              | private, id, created_at                 |                      | ApiInfoController#show                                                   |
| repo_subscriptions | user_id, last_sent_at               | user_id              | SendDailyTriageEmailJob#email_sent_today?                                |
| repo_subscriptions | repo_id, user_id                    | repo_id              | DocMethodsController#click_method_redirect                               |
| issue_assignments  | repo_subscription_id, created_at    | repo_subscription_id | SendSingleTriageEmailJob#assignment                                      |
| issue_assignments  | repo_subscription_id, delivered     | delivered            | User#issue_assignments_to_deliver                                        |
| repos              |                                     | name                 | redundant index, [name, user_name] should take care of it                |
| doc_assignments    | repo_subscription_id, doc_method_id | repo_subscription_id | DocMethodsController#click_method_redirect                               |
| doc_methods        | repo_id, doc_comments_count         | repo_id              | Repo#methods_missing_docs                                                |
| doc_classes        | repo_id, doc_comments_count         | repo_id              | Repo#classes_missing_docs                                                |
| issues             | repo_id, state                      | state                | Repo#force_issues_count_sync! (state is nowhere queried without repo_id) |

> I can create a PR if this looks decent. @schneems @nateberkopec

**Comment by nateberkopec** [comment]
😍 Gorgeous, how did you come up with this list?

**Comment by anmolarora** [comment]
Well, this was a manual effort.
Searched for all the occurrences of `.where` in the code.

**Comment by nateberkopec** [comment]
Impressive!
