### ISSUE TITLE
Url input color not readable

### ISSUE THREAD

**Issue by k-awe-some** [codetriage/codetriage#1097]
## Expected Behavior
On adding a new repo, users should be able to easily read placeholder text for instructions as well as their input for confirmation before submitting.

## Current Behavior
I noticed **unless the user choose from their broswer default dropdown**, the url input field is of some sort of black color which is not readable on the dark background.

![url-field-color-bug](https://user-images.githubusercontent.com/49572628/65978833-61b90280-e442-11e9-9b25-8772200ee553.png)

## Possible Solution
Updating css `color` value for text-typed `input`. I've made [this PR](https://github.com/codetriage/codetriage/issues/1097#issue-501026171) to cover the solution.

## Your Environment

* Browser: Chrome
* Version: 77.0.3865.90 (64-bit)

**Comment by schneems** [comment]
We good?
