### ISSUE TITLE
Too many emails. Inability to unsubscribe. 

### ISSUE THREAD

**Issue by onlyanegg** [codetriage/codetriage#1246]
You send me an email like every week saying Code Triage misses you. I can't unsubscribe. The only thing I can do is remove my account which I don't want to.

**Comment by schneems** [comment]
The only thing this app does is send emails. Unsubscribing would be the same thing as deleting your account.

**Comment by razum2um** [comment]
I think it's not clear from that deletion page, so I suggest to add those lines https://github.com/codetriage/CodeTriage/pull/1506

**Comment by schneems** [comment]
Great idea. Done.
