### ISSUE TITLE
Language menu show all languages twice

### ISSUE THREAD

**Issue by AmrDeveloper** [codetriage/CodeTriage#1294]
In the Main layout when I opened the language menu I got all languages twice in the menu
I tested in from Desktop pc and android device

## Expected Behavior
The languages menu must show all languages once

## Current Behavior
The languages menu show all languages twice

## Screenshot
![screenshot](https://user-images.githubusercontent.com/23631699/80926024-c18ad980-8d94-11ea-8d12-d31e5b026ae1.PNG)

## Your Environment
* Browser Name and version: Firefox 75
* Operating System and version (desktop or mobile): Windows 10

**Comment by ashishra0** [comment]
If this issue is sorted out, then close this issue 👍
