### ISSUE TITLE
Filter list by Language shows the same 13 projects for all the languages

### ISSUE THREAD

**Issue by AdityaJ7** [codetriage/CodeTriage#1314]
The Filter by Language search under the "Triage Open Source Issues, Squash COVID-19" Heading shows the same 13 projects irrespective of the language chosen by the user.

## Current Behavior
The filter shows the following result for all the languages:(I have attached Screenshots for only four:-Python, C, C++, Nim)
![Screenshot (279)](https://user-images.githubusercontent.com/42397096/84024603-ca7c5580-a9a7-11ea-8ea1-9506b8b8a041.png)
![Screenshot (280)](https://user-images.githubusercontent.com/42397096/84024613-d36d2700-a9a7-11ea-8b60-69fc10439972.png)
![Screenshot (277)](https://user-images.githubusercontent.com/42397096/84024627-d8ca7180-a9a7-11ea-95d4-56fa2a3226f6.png)
![Screenshot (278)](https://user-images.githubusercontent.com/42397096/84024643-df58e900-a9a7-11ea-9eba-77aedf05a658.png)

## Expected Behavior
The search result should show projects related to the language provided in the filter.

## Possible Solution
All the searches point to the same result so proper filtering of results must be done

## Steps to Reproduce (for bugs)

1. Go the website.
2. Choose any language of your choice in the filter list by language dropdown under the 'Triage Open Source Issues, Squash COVID-19' heading and notice the result of the filter.
3. Choose another language and compare the filter result.
4. You will find both provide the same search result.

## Context
I was trying to filter the COVID-19 related projects for Go language but I don't trust the search results I see. 

## Your Environment

* Browser Name and version: Chrome Version 83.0.4103.61
* Operating System and version (desktop or mobile): Desktop with Windows 10

**Comment by Cueball** [comment]
Dup of #1305
