### ISSUE TITLE
Logging in after logout does not ask for authentication

### ISSUE THREAD

**Issue by kinekt4** [codetriage/CodeTriage#1372]
When a user logs-out, then tries to log back in, there is no authentication form.

## Expected Behavior

An authentication form should be presented.

## Current Behavior

The website allows the user to log straight back in without authentication.

## Possible Solution

Logging out should destroy all login tokens and cookies. And an authentication form should be presented.

## Steps to Reproduce (for bugs)

1. Log into codetriage.com (github, 2FA)
2. Click "Sign Out" button
3. It appears the user is logged out.
4. Click "Log In" button
5. The user is logged straight back in without entering any authentication details.

This appears to happen even after the user has closed the browser, then re-opened it.

## Context

I believe this is a  security/privacy issue. Logging out should destroy all tokens and cookies.

## Your Environment

* Version used: current
* Browser Name and version: Opera 70.0.3728, Firefox 80.0.1, Microsoft Edge 85.0.564
* Operating System and version (desktop or mobile): Windows 10 (64bit) Desktop
* Link to your project:

**Comment by schneems** [comment]
This is the Oauth flow. That's github's decision to show you a "do you want to grant permission" or not. You've already granted permission so they return quickly. This is how all github Oauth flows work.
