### ISSUE TITLE
Unauthed users with a direct link get an error instead of an auth screen

### ISSUE THREAD

**Issue by filiptronicek** [codetriage/CodeTriage#1499]
## Expected Behavior
When visiting a CodeTriage link such as https://codetriage.com/aperta-principium/Interclip (without being authed), I get an error. 

## Current Behavior
I get redirected to `https://www.codetriage.com/users/auth/github?origin=%2Frepos%2Fnew%3Fname%3DInterclip%26user_name%3Daperta-principium` and get the following error:
```
Not found. Authentication passthru.
```

## Possible Solution
Redirect the user to an auth screen and redirect him back upon login.

## Steps to Reproduce (for bugs)
1. Ensure you are not logged in to CodeTriage
2. Go to `https://codetriage.com/someuser/somerepo`

## Context
Originally reported by @diminutivesloop in https://github.com/open-sauced/open-sauced/issues/979.

## Your Environment

* Version used: Probably latest
* Browser Name and version: Firefox 89
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://codetriage.com/aperta-principium/Interclip

**Comment by schneems** [comment]
I think the problem is github changed their authentication. They've been emailing me that it's deprecated but I've not been able to update it yet.

**Comment by filiptronicek** [comment]
That sounds like an awesome idea! If we wanted to make it automatic, we could create an invisible form with a POST action and submit it with JS 👀

**Comment by mtfoley** [comment]
@filiptronicek i didn’t link to this issue in the PR correctly, I think it can be closed.

**Comment by filiptronicek** [comment]
Yes, @mtfoley, thanks a lot for contributing the fix! 🧡
