### ISSUE TITLE
Put the "STOP TRIAGING" button at the top of the page

### ISSUE THREAD

**Issue by vhouriet** [codetriage/CodeTriage#1573]
## Expected Behavior

When on the page of a repo on the website, the important actions should be immediately visible. So "STOP TRIAGING" should be near the top with the other actions, like "SEND ME A NEW ISSUE!" and "Triage Docs!" and not at the bottom of the page.

## Current Behavior

Users shouldn't have to scroll to the bottom of the page for a basic functionnality.

## Possible Solution

Put the "STOP TRIAGING" button above Subscribers list as it is more relevant in my opinion.

## Context

The way it currently works is not very usery friendly. I spend sometime looking for that option which is a pretty basic one that should be easy to access.

**Comment by maco** [comment]
@schneems should this be closed since it's now above the subscriber list?
