### ISSUE TITLE
How can I add my project?

### ISSUE THREAD

**Issue by Leia286** [codetriage/CodeTriage#1576]
I'd like to add [RandomCSS](https://github.com/Leia286/RandomCSS), please. It is written in CSS and YML and needs some help. It uses the  GPL-3.0 License. I'd like some help, especially with YML, as I don't really know YML and kinda want to make sure it's functional. We are doing Hacktoberfest as well!

**Comment by schneems** [comment]
https://www.codetriage.com/repos/new
