### ISSUE TITLE
Previous and next links don't persist the chosen language

### ISSUE THREAD

**Issue by kgrz** [codetriage/codetriage#160]
When I click the "Add a repo" button, this is the first page that gets shown:

![Index page of "Add a repo" feature page](http://f.cl.ly/items/0P3b1q0s1A0H2l0N0703/Image%202013.08.15%209%3A21%3A12%20PM.png)

After I click the `next page` link, the left sidebar gets changed and the language filtering gets messed up:

![After clicking next link](http://f.cl.ly/items/1D1n2Z0M1k0g3w0M2D2y/Image%202013.08.15%209%3A21%3A56%20PM.png)

**Comment by schneems** [comment]
I think this was fixed kinda. It looks like the pagination was taken away
