### ISSUE TITLE
Nyxt Browser shows as Next

### ISSUE THREAD

**Issue by vovi-z** [codetriage/CodeTriage#1650]
## Expected Behavior
Code Triage should link to Nyxt Browser.
Next Browser [renamed](https://nyxt.atlas.engineer/article/next-nyxt-rename.org) itself to Nyxt Browser in 2020.

## Current Behavior
Currently Code Triage shows Next Browser.

## Steps to Reproduce (for bugs)
https://www.codetriage.com/atlas-engineer/next

**Comment by schneems** [comment]
I renamed it https://www.codetriage.com/atlas-engineer/nyxt
