### ISSUE TITLE
Port tests over to github actions

### ISSUE THREAD

**Issue by schneems** [codetriage/CodeTriage#1685]
## Expected Behavior

When contributors open up PRs tests should run

## Current Behavior

Heroku CI only runs for branches inside of the same repo. So when a contributor opens a PR their tests don't run.

## Possible Solution

Keep the Heroku tests for now, but ALSO introduce GitHub actions to test the codebase

I'll gladly tag it #hacktoberfest 🙏🏻

**Comment by shivam-sharma7** [comment]
can you assign me?

**Comment by schneems** [comment]
Done

**Comment by schneems** [comment]
Hello. I’m am curious what you think the timeline is for this issue.

**Comment by schneems** [comment]
Hi. I've not heard from you in some time. You're still welcome to work on this, but I also want to open it up. Not having tests trigger on contributor PRs is a bit of a bottleneck during hacktoberfest.

**Comment by deepakmahakale** [comment]
Anyone working on this one?

**Comment by deepakmahakale** [comment]
We could change this the way we did for wicked

**Comment by shivam-sharma7** [comment]
> deepakmahakale

you can work now. @deepakmahakale

**Comment by deepakmahakale** [comment]
@schneems should I start on this?

**Comment by gregmolnar** [comment]
@deepakmahakale We are planning to pair on this with @neko314

**Comment by deepakmahakale** [comment]
> @deepakmahakale We are planning to pair on this with @neko314

Wonderful 👍
