### ISSUE TITLE
Upgrade Ruby to 3.1.2

### ISSUE THREAD

**Issue by schneems** [codetriage/CodeTriage#1701]
Update the version in the Gemfile to allow 3.1.x and update the entry in the Gemfile.lock.

Run tests locally and fix failures/deprecations. `bundle exec rubocop && bin/rails test`

**Comment by hbontempo-br** [comment]
Can this be closed?
Forgot to add the 'closes #1701' on the PR

**Comment by schneems** [comment]
Yep, thanks!
