### ISSUE TITLE
Upgrade Rails versions

### ISSUE THREAD

**Issue by schneems** [codetriage/CodeTriage#1702]
Update the version in the Gemfile and run `bundle update rails` https://guides.rubyonrails.org/upgrading_ruby_on_rails.html. Fix issues as they come up.

Run tests locally and fix failures/deprecations. `bundle exec rubocop && bin/rails test`.

**Comment by avcwisesa** [comment]
Hi! I'm new to OSS contribution. Have carefully read the guides & made sure tests are passing. Let me know if I missed anything. Thank you :)

**Comment by schneems** [comment]
You did great, thanks! In the future you can also add `closes #1702` and it will auto-close the issue you linked (this one). It's not crucial, but it's a nice touch.
