### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by catsby** [codetriage/CodeTriage#173]
I try logging in, but I get the old "We're sorry, but something went wrong." Rails error :/ 

I think I ran into this in the past involving my email address according to GitHub (being public or not). I made it public again, but nothing..

**Comment by spidergears** [comment]
I do not seem to have changed anything on my github page.
I am facing the same issue, although I receive periodic reminders from Codetriage on my listed email account. 

Also I checked today, CodeTriage is not listed in my authorized application on github but when I try to sign up with github, I see the same rails error Page. Screeshot attached.

Pls. suggest something.

![codetriage](https://cloud.githubusercontent.com/assets/3817081/5888660/6e42e574-a42e-11e4-9569-8ce36d3de17b.jpg)

**Comment by schneems** [comment]
The spelling is apparently case sensitive for github. `SpiderGears` and `spidergears` are two different users.
