### ISSUE TITLE
GDPR deletion request

### ISSUE THREAD

**Issue by Tabby** [codetriage/CodeTriage#1767]
As the issue I previously created (#1593) has been ignored, meaning that I still cannot login to delete my account and am still being sent unwanted emails frequently, I am hereby requesting immediate erasure of personal data concerning me according to Article 17 of the GDPR.

My account on CodeTriage is still using my old GitHub username: @jooles. Please delete the entire account and all associated data

I am of the opinion that the requirements set forth in Article 17(1) GDPR are fulfilled. You cannot claim an exception based on Article 17(3) GDPR either, particularly as I am not a public figure.

If I have given consent to the processing of my personal data (e.g. according to Article 6(1) or Article 9(2) GDPR), I am hereby withdrawing said consent for the entire process.
In addition, I am objecting to the processing of personal data concerning me (which includes profiling), according to Article 21 GDPR. I request that you restrict the processing of the data concerning me pending the verification whether your legitimate grounds override mine, pursuant to Art. 18(1)(d) GDPR.

If you have made the aforementioned data public, you are obliged pursuant to Article 17(2) GDPR to take all reasonable steps to inform other controllers, including search engine operators, who process the personal data listed above, that I have requested the erasure of all links, copies or replications. This applies not only to exact copies of the data concerned, but also to those from which information contained in the data concerned can be derived.

In case you have disclosed the affected personal data to third parties, you have to communicate my request for erasure of the affected personal data, as well as any references to it, to each recipient as laid down in Article 19 GDPR. Please also inform me about those recipients.

If you object to the requested erasure, you have to justify that to me.

My request explicitly includes any other services and companies for which you are the controller as defined by Article 4(7) GDPR.

As laid down in Article 12(3) GDPR, you have to confirm the erasure to me without undue delay and in any event within one month of receipt of the request.

Thank you in advance.

**Comment by schneems** [comment]
I'm unable to find `jooles` but I did find a `Jooles` I can't confirm that's you from public information (it's not tied to your github) so i'll send you an email shortly. Reply to that and I can delete your account.

**Comment by Tabby** [comment]
Email replied to and I've been assured that the data has been deleted (which is good enough for me 🙂)
