### ISSUE TITLE
Replace the obsolete Travis CI badge

### ISSUE THREAD

**Issue by jhsu802701** [codetriage/CodeTriage#1769]
This repository has replaced the obsolete Travis CI builds with GitHub Workflows CI builds.

## Expected Behavior
The README.md page should display a badge showing the status of the GitHub Workflows CI build.

## Current Behavior
The README.md page still displays the Travis CI badge.

## Possible Solution
Update the README.md page to display the new CI badge instead of the old and obsolete one.

## Context
This app works with the wrong CI badge, but it's more difficult to see the results of the current CI build system.

**Comment by mishina2228** [comment]
#1750 has been merged and this issue can be closed.
