### ISSUE TITLE
Deleted my account but still received emails!

### ISSUE THREAD

**Issue by AbeTavarez** [codetriage/CodeTriage#1786]
Hello, I need help deleting my account completely.

## Description 
I signed up using my github account (AbeTavarez) last year. I deleted my account but I’m still getting all emails notifications. I tried signing up again and deleting my account again and nothing changed.

## Expected Behavior
I need to stop all notifications coming from your app asap, I’m missing important emails because of the amount of emails send a day.

## Current Behavior
Currently is sending dozens of emails per day.

Is this the best way to solve this issue?
Please help!

**Comment by schneems** [comment]
Looking at this now

**Comment by schneems** [comment]
I don't see a user with your github username in the database. Are you still getting emails? Can you send me the email address you're getting them delivered to? If you don't want to post it here you can find my email address in my github profile.

**Comment by schneems** [comment]
I got one other report at around the same time. I'm wondering what you see when you click the "delete" link. I'm thinking maybe sendgrid had a short outage for their URL service.

**Comment by AbeTavarez** [comment]
Hey thank for looking into this. 
My email is abeincwireless@gmail.com

**Comment by AbeTavarez** [comment]
When I clicked on the delete link it just confirmed that I wanted to delete the account and it logged me out.

**Comment by schneems** [comment]
Think you're out of the DB, let me know if you're still getting emails.
