### ISSUE TITLE
HashiCorp repos no longer licensed Open Source

### ISSUE THREAD

**Issue by boldandbusted** [codetriage/CodeTriage#1800]
Howdy. Just FYI, all HashiCorp repos are no longer licensed as Open Source (as defined by the OSI), as they've been relicensed as the BSL. OpenTofu is a fork of Terraform, so that might be worth adding to CodeTriage, if it isn't already.

Some examples of HashiCorp projects no longer Open Source:
* Terraform
* Vault
* Nomad
* Vagrant
* Packer
* Waypoint
* Boundary
* Consul

Sad to write this. :( Thanks.

**Comment by schneems** [comment]
> so that might be worth adding to CodeTriage

Anyone can add any repo to CodeTriage regardless of license if it's public
