### ISSUE TITLE
How about having a grid view instead of a list view for listing out the repos that need help? 

### ISSUE THREAD

**Issue by murtuzakz** [codetriage/codetriage#224]
A lot of wasted space on left and right of the app due to this, and overly long pages.

**Comment by AnneTheAgile** [comment]
+1 I'd love to see this. It would condense viewing, great with so many repos.

**Comment by tejasbubane** [comment]
I would also like to see `triage/untriage` button alongside the project names. This would help to quickly manage subscriptions to different projects.

**Comment by jacemonje** [comment]
Hey guys, we've made some proposed changes to the UI to improve user experience. Would love to get your thoughts. :)

https://github.com/codetriage/codetriage/pull/352

**Comment by prathamesh-sonpatki** [comment]
Closing this as we got new design. Thanks for the suggestions everyone!
