### ISSUE TITLE
Provide Badges

### ISSUE THREAD

**Issue by h4cc** [codetriage/codetriage#268]
How about providing badges the project can add to ther README.md?

That would help the project finding helpers, as well as codetriage to become more popular.

**Comment by marceloboeira** [comment]
@schneems I know that can be hard, but would even be nicer to have a setup file to the amount of issues and colors.  Like:
`.triage.yml`

```ruby
red: 0
orange: 1-2
yellow: 5-10
....
```

To be decided:

* Would we create/serve the SVG's dynamically (run time)? Or redirect to shield.io service?
* Will we use a setup file on the "client" repository to setup this?

If you decide yourselves soon I can work on a pull request.

**Comment by parndt** [comment]
@BanzaiMan sorry to weave you in, but given you've deal with badges for Travis CI, how did you all end up handling it? Is there some prior art we should just use?

**Comment by BanzaiMan** [comment]
Actually, I haven't. I didn't really touch this stuff.

What I do know is that we have a set of SVG files (in https://github.com/travis-ci/travis-api/tree/master/public/images/result) and serve them up from API (a Sinatra app) according to the status.

**Comment by parndt** [comment]
@BanzaiMan awesome, thanks for the knowledge!

**Comment by marceloboeira** [comment]
@parndt that wouldn't be the best choice here, since we need to show numbers. We really need a SVG generator, to create dynamic stuff like:

![triagers](https://img.shields.io/badge/triagers-10-red.svg)
![triagers](https://img.shields.io/badge/triagers-1325-blue.svg)

**Comment by BanzaiMan** [comment]
I reckon Code Climate or Coveralls would have some insight into how to do such a thing.

**Comment by nateberkopec** [comment]
![screen shot 2017-05-27 at 5 17 02 pm](https://cloud.githubusercontent.com/assets/845662/26524856/51ef971e-4300-11e7-873a-64d80d15bc8c.png)
