### ISSUE TITLE
Assets are not loaded in Chrom(e|ium) with HTTPS Everywhere installed

### ISSUE THREAD

**Issue by develop7** [codetriage/CodeTriage#275]
Repro: navigate to codetriage.com

Expected: ![screenshot from 2014-10-28 20 07 41](https://cloud.githubusercontent.com/assets/89889/4813046/134b796e-5ec5-11e4-830b-b3193f8f8571.png) (Firefox)

Instead: 
![image](https://cloud.githubusercontent.com/assets/89889/4813069/405726a6-5ec5-11e4-8bc8-bb5658d4a193.png)

Console dump:

```
https://issuetriage.herokuapp.com.global.prod.fastly.net/assets/application-d0e099e021c95eb0de3615fd1d8c4d83.css Failed to load resource: net::ERR_INSECURE_RESPONSE
https://issuetriage.herokuapp.com.global.prod.fastly.net/assets/application-97e9bbdbd3f560742d2c32c89adef23e.js Failed to load resource: net::ERR_INSECURE_RESPONSE
```

And it is indeed: https://issuetriage.herokuapp.com.global.prod.fastly.net/assets/application-d0e099e021c95eb0de3615fd1d8c4d83.css presents following page: 
![image](https://cloud.githubusercontent.com/assets/89889/4813146/dbaec4a6-5ec5-11e4-8355-cdb968c64184.png)

Environment: Chromium v39.0.2171.27 (Developer Build)

**Comment by connor11528** [comment]
Sorry to bring this back from the dead but I am getting the same error. Do you remember what the fix was?

**Comment by develop7** [comment]
@connor11528 I believe it was disabling the `Fast.ly` rule, but it's ineffective now (there's dedicated `Codetriage` rule instead). Is your HTTPS Everywhere installation up-to-date?

**Comment by connor11528** [comment]
I had https everywhere forced in my app and that was actually the breaking change. My app is on http so the browser didn't like the https requests for some reason. It was a small headache but once turned off the https my site is hosted on heroku and live with google domains - http://www.employbl.com/

**Comment by schneems** [comment]
All assets and the website should be served via HTTPS. Is there something I need to do to fix?

**Comment by connor11528** [comment]
No you're all good my bad
