### ISSUE TITLE
Welcome email with a link to the wrong repository

### ISSUE THREAD

**Issue by nathany** [codetriage/codetriage#298]
When I subscribed to this repository, the welcome email contained a link and title for an issue in another repository entirely:

https://github.com/joefitzgerald/go-plus/issues/101

```
You signed up to help triage GitHub issues on golang/go. That's pretty awesome.

Triage Issue: golang/go#101

autocomplete-plus completion not working with go-plus

Goals of Triage

Help share the weight of maintaining a project
Minimize un-needed issues
Prevent stale issues
Encourage productive communication
Teach good citizenship
To become a better coder
```

I also subscribed to another repository, which worked fine. Both of these were first-time subscriptions setting up CodeTriage for the repository.

**Comment by spidergears** [comment]
@nathany Can list out the steps to reproduce this?

**Comment by nathany** [comment]
No. I don't think it's reproducible. It only happened once of all the times I've subscribed to a repository. Like a race condition or something.

**Comment by igas** [comment]
I think I fixed it in #289

**Comment by nathany** [comment]
Both these repos had a fair number of issues, though maybe that fix also fixes this too?

**Comment by schneems** [comment]
Haven't seen this come up again
