### ISSUE TITLE
the question under unsubscribe is a flash message that disappears after a few seconds

### ISSUE THREAD

**Issue by cebe** [codetriage/codetriage#299]
I just unsubscribed and found that the question that asked me if I really wanted to was disappearing after 1-2 seconds, not helpful if I wanted to double check what was written there :)

Url: `http://www.codetriage.com/users/unsubscribe/<a really long hash>`

**Comment by mario-d-s** [comment]
@cebe Is this still an issue? 

I'm not sure what "unsubscribe" is supposed to mean in this context. I tried clicking "stop triaging" and there was a standard browser confirm dialog (OK / cancel). I tried deleting my account and landed on a separate page asking for confirmation.

I think this issue can be closed.

**Comment by cebe** [comment]
can't remember what this was about if it works for you, close it.
