### ISSUE TITLE
Error when click in "Send new Issue"

### ISSUE THREAD

**Issue by duduribeiro** [codetriage/codetriage#307]
I'm trying to click in "Send new Issue" button in http://www.codetriage.com, but I get a "We're sorry, but something went wrong"
![click_button](http://i.imgur.com/QSYmntY.png)
![error](http://i.imgur.com/weviO75.png)

When running local, the IssueAssignmentsController is trying to call a undefined_method
![error_desc](http://i.imgur.com/eXIDR9L.png)

**Comment by prathamesh-sonpatki** [comment]
Closed by #308
