### ISSUE TITLE
Subject line in daily triage email incorrectly pluralizes "issue"

### ISSUE THREAD

**Issue by iKevinY** [codetriage/codetriage#312]
I configured my account to only send one issue per day, but the subject line reads "Help Triage 1 Open Source Issues". Ruby is completely out of my depth, but could this be due to `@assignments.count` not returning the correct value [here](https://github.com/codetriage/codetriage/blob/master/app/mailers/user_mailer.rb#L13) in `UserMailer`? (Would changing `.count` to `.size` fix the issue?)

![CodeTriage Subject Line](https://cloud.githubusercontent.com/assets/2434728/6142444/6e6d0d8c-b16b-11e4-971e-a95ed27fab01.png)

**Comment by marceloboeira** [comment]
@iKevinY I guess that is not the case, `.count` is used because `@assigments` can be nil/empty I guess, and `size` is only for array instances. I would say to change it anyway, because you need to trust your own inputs, now coming from front-end/client ...

**Comment by O-I** [comment]
@iKevinY Interesting. I tried to reproduce this by setting my max issue per day count to 1. I just got my triage email and it displays "Help Triage 1 Open Source Issue" correctly. Can you pop in and let us know if the problem persists in your next email?

**Comment by iKevinY** [comment]
@O-I Sure. The email I received shortly before your comment still read "1 Open Source Issues" – I'll comment again after getting tomorrow's email.

**Comment by iKevinY** [comment]
The email I received today also reads "1 Open Source Issues".

**Comment by O-I** [comment]
@iKevinY OK. Thanks for letting me know. I'm pretty sure what you suggest will fix this, but looking into this [commit](https://github.com/codetriage/codetriage/commit/56ef475d1ea9a847ea2261a3faf9c53fd2dfddb8) and associated Rails [issue](https://github.com/rails/rails/issues/16171) to understand why.

**Comment by iKevinY** [comment]
@O-I Want me to open a PR making that change?

**Comment by O-I** [comment]
Go for it. It looks like an innocent enough fix.

**Comment by iKevinY** [comment]
Looks like #313 did the trick! My latest triage email correctly reads "1 Open Source Issue".

**Comment by schneems** [comment]
Great! Thanks.



—
