### ISSUE TITLE
on line 9: syntax error, unexpected ':', expecting $end

### ISSUE THREAD

**Issue by wangbourne** [codetriage/codetriage#324]
I got following errors when trying to execute bundle install:

Gemfile syntax error compile error
on line 9: syntax error, unexpected ':', expecting $end
gem 'puma_auto_tune', github: "schneems/puma_auto_tune"

I'm using: Ruby 1.8.7;  Bundle 1.9.2;

**Comment by prathamesh-sonpatki** [comment]
@wangbourne We are using Ruby 2.2.1. Please use this Ruby and then you will not face any problem. This error is causing because Ruby 1.8.7 does not support new hash syntax `key: value`.
