### ISSUE TITLE
Exception when submitting a duplicate Repo, rather than error message

### ISSUE THREAD

**Issue by chrisccerami** [codetriage/codetriage#335]
Similar to #314, page crashes when user tries to submit a repo that's already been submitted rather than re-rendering the page with an error message.

**Comment by chrisccerami** [comment]
I've got a few failing tests in this PR that I'm still trying to correct.

**Comment by chrisccerami** [comment]
Tests are passing now. I was having an issue with the test that expect the mailer to not send mail for a repo without issues. I had to rerecord the cassette for that request, and I guess the repo that was previously being used now has issues on it, so I switched it to use a different repo and recorder that response to the cassette. Everything should be good now.

**Comment by prathamesh-sonpatki** [comment]
Closing this since #336 got merged.

**Comment by chrisccerami** [comment]
Thanks. Totally forgot about this issue.
