### ISSUE TITLE
Not receiving emails from CodeTriage

### ISSUE THREAD

**Issue by msbukkuri** [codetriage/codetriage#343]
I am not sure if this is correct place to raise this issue. But I used to use CodeTriage few months ago. At some point, I stopped emails from CodeTriage since I was not using it.

I would like to start using it again, so I subscribed to some repos, and changed my "Max # of issues you want to receive per day" to 3.

But I am no longer receiving any emails from CodeTriage. Please help.

My username is the same as my Github user name @msbukkuri.

**Comment by schneems** [comment]
What project did you subscribe to?

**Comment by msbukkuri** [comment]
Hey @schneems, thanks for your quick response. I subscribed to 3 projects that have high requests:
meteor (meteor/meteor)
gitlabhq (gitlabhq/gitlabhq)
atom (atom/atom)

**Comment by msbukkuri** [comment]
Gave it a couple of days, still not receiving anything. Any thoughts on this?

**Comment by msbukkuri** [comment]
Closing this issue. This was definitely a PEBKAC. I had unsubscribed from CodeTriage on https://unroll.me. So that was the issue.
