### ISSUE TITLE
Edit Repository Authorization

### ISSUE THREAD

**Issue by CjayBillones** [codetriage/codetriage#347]
![bug - edit not found](https://cloud.githubusercontent.com/assets/8434127/8098778/bbbd5802-1026-11e5-8fc2-1bcad8332d90.png)

What happens is that I can't edit the repository even if I own it.

**Comment by CjayBillones** [comment]
I already found out what's wrong with this and I can apply the necessary solution to fix this minor bug. :)

**Comment by prathamesh-sonpatki** [comment]
@CjayBillones Closing this issue as you fixed it already :smile:

**Comment by CjayBillones** [comment]
Alright! Thanks a lot! :)
