### ISSUE TITLE
Pagination on Repos index view doing a crazy

### ISSUE THREAD

**Issue by sarahjschultz** [codetriage/codetriage#393]
Hey there! 
Noticed an issue with inconsistency of pagination styling on the Repos index page, this morning. 

To Reproduce: 
- Be signed in
- Navigate to Repos (codetriage.com/repos)
- Scroll to bottom of page where pagination lives
- See this:   
![bad_pagination](https://cloud.githubusercontent.com/assets/1680359/10258784/930e94a6-691e-11e5-8973-81f49e2f4b5b.png)

I actually had a moment to spare this afternoon and fixed it. Will link the PR to this issue momentarily -- please let me know if I am missing some other preferred protocol for submitting fixes! Thanks :dancer:

**Comment by prathamesh-sonpatki** [comment]
This can be closed now as we got new design. Thanks for your help :smile:

**Comment by sarahjschultz** [comment]
@prathamesh-sonpatki Awesome -- love the new design! :beers:
