### ISSUE TITLE
Front Page Width

### ISSUE THREAD

**Issue by schneems** [codetriage/codetriage#402]
The width of the "select language" is wider than the minimum width of the homepage, this gives us a small border on the right when viewing on my iphone 6s plus

![](https://www.dropbox.com/s/fo4hrz41tgbohut/Screenshot%202015-10-13%2009.57.14.png?dl=1)

**Comment by prathamesh-sonpatki** [comment]
Can this be closed now as #406 got merged?

**Comment by schneems** [comment]
yes, thanks
