### ISSUE TITLE
No unsubscribe link on automated emails

### ISSUE THREAD

**Issue by hamitron** [codetriage/codetriage#409]
![screen shot 2015-10-27 at 12 27 00 pm](https://cloud.githubusercontent.com/assets/5580700/10769982/301df6f2-7ca6-11e5-9912-c7c20c40650d.png)

There is no unsubscribe link available on an automated e-mail.  At least in my opinion, its more important than the link to delete your account.  I can't seem to find the proper link for any FCC regulation, but I'm pretty sure its recommended to have.

**Comment by schneems** [comment]
Deleting your account unsubscribes. The regulations you're looking for is https://en.wikipedia.org/wiki/CAN-SPAM_Act_of_2003.

**Comment by hamitron** [comment]
what if I don't want to delete my account?

**Comment by schneems** [comment]
This is an email only app. Unsubscribing from email means you effectively don't have an app, which is effectively the same thing as deleting your account. What reasons would you have for unsubscribing but not deleting?

**Comment by hamitron** [comment]
I guess I just get too many e-mails already, and would rather interact directly with the site.

**Comment by schneems** [comment]
Interesting, maybe we can change this later. For example if we made a dashboard, but for now we don't have anything like that. For now maintaining a separate suppression list would add overhead and complexity.

**Comment by Sja91** [comment]
What if you were only wanting to disable the emails temporarily? Life happens.

**Comment by schneems** [comment]
You can manually set your frequency to “monthly”.
