### ISSUE TITLE
Can't search for C# projects

### ISSUE THREAD

**Issue by frickinjason** [codetriage/codetriage#412]
It looks like the # isn't making it and only C projects are being returned.

**Comment by schneems** [comment]
This is an implementation artifact. You can manually search http://www.codetriage.com/?language=C%23

We need to switch the homepage to use something like turbolinks instead of trying to get all fancy with ajax (is what i'm thinking right now).

**Comment by prathamesh-sonpatki** [comment]
Closing this as #425 got merged.
