### ISSUE TITLE
Screen formatting disappears

### ISSUE THREAD

**Issue by jhstephenson** [codetriage/codetriage#416]
After viewing the list of Rails Issues, when I click the back button the attached screen comes up
![codetriagescreencapture](https://cloud.githubusercontent.com/assets/772922/11120068/eb6e1c28-890a-11e5-9b8b-36b02f957473.PNG)

I have duplicated it several times. The order I viewed things in was:
1. Select language: Ruby
2. Select Project: Rails
3. View list of issues
4. Click back button

**Comment by schneems** [comment]
Thanks. I'm pretty sure that's due to the way I implemented paginating on the home page with JS. I'm not quite sure why it's happening. I'm looking into alternate methods to get a similar effect.

**Comment by jhstephenson** [comment]
No problem. I was just hoping it wasn't something screwed up in my Chrome
browser.

**Comment by prathamesh-sonpatki** [comment]
@schneems @jhstephenson Found a related SO question to this issue here http://stackoverflow.com/questions/13130216/being-served-a-response-directly-from-the-cache-when-clicking-back-button. There has been an open issue related to this too https://github.com/rails/jquery-ujs/issues/318

**Comment by prathamesh-sonpatki** [comment]
Closing this in favor of #437 and #455.
