### ISSUE TITLE
Unselected values difficult to read in "Triage More" selector

### ISSUE THREAD

**Issue by cbzehner** [codetriage/codetriage#432]
Number of items to triage dropdown has no contrast between unselected options value and background. Tested on Linux Mint (Ubuntu-derivative) and Windows 10 on Chrome for repro.

Steps:
1) Login with Github
2) Go to repro and select "I want to triage"
3) Choose selector under "Triage more or less" and see values which display as hard to read.

![codetriage colors](https://cloud.githubusercontent.com/assets/3886290/12223970/78487d42-b79a-11e5-92c2-13338d6f060e.JPG)

**Comment by schneems** [comment]
I can't see that on my mac :( Can you attempt a fix? I think maybe we should explicitly set the color of the text.

**Comment by cbzehner** [comment]
Definitely. I'll look into it this weekend.

**Comment by mjhoy** [comment]
I see it on FF 44.02, osx 10.9

adding the rule

    .repo-instructions select { color: black; }

fixed it for me.

**Comment by prathamesh-sonpatki** [comment]
Fixed by https://github.com/codetriage/codetriage/pull/495
