### ISSUE TITLE
random 404 not found when trying to triage

### ISSUE THREAD

**Issue by ssoulless** [codetriage/codetriage#434]
Hi, I have noticed that for some of the projects when you click the "I want to triage" button

For example one of the projects that presents this problem is cancancan
https://t.co/CExehB3w8e

and some others

**Comment by schneems** [comment]
I had this happen once, going back and clicking the button again fixed it and I was able to subscribe. I don't know what caused the problem.

**Comment by tejasbubane** [comment]
Stumbled across this thing today. The issue is that `I want to triage` button still has `/repo_subscriptions?repo_id=1209` link even though I am logged out. (Happens only in normal window where I was logged in at some point of time before, not in incognito).

**Comment by prathamesh-sonpatki** [comment]
Yeah, this issue happens when we are not logged in but click on `I want to triage`. Devise logs you in and then tries to redirect a POST request resulting into 404.

**Comment by schneems** [comment]
We should probably check if you're logged in or not, if you're not keep the button but have it go to signup instead of posting to the subscribe endpoint.

**Comment by prathamesh-sonpatki** [comment]
:+1: @tejasbubane want to take a stab at implementing it?

**Comment by mbie** [comment]
I think that this issue can be closed. I'm still getting codetriage notifications for it :)

/cc @prathamesh-sonpatki
