### ISSUE TITLE
JSON shown when reopening closed tab

### ISSUE THREAD

**Issue by alex88** [codetriage/codetriage#437]
Steps to reproduce:

 - open with firefox/chrome (tested on Chrome 49.0.2618.8 and FF 43.0.4) with at least 2 tabs
 - go to http://www.codetriage.com/, select a language (e.g. PHP)
 - url becomes http://www.codetriage.com/?language=PHP
 - close tab
 - reopen last tab

now it shows the JSON response from the server instead of the HTML of the page.
I know it's an edge case but reported anyway :wink:, just in case.

**Comment by BuKinoshita** [comment]
:+1:

**Comment by blakeyc** [comment]
Same happens if you use the back and forward buttons in the browser. Using Chrome Version 48.0.2564.116 (64-bit)
