### ISSUE TITLE
Filter list by multiple languages

### ISSUE THREAD

**Issue by vishalkuo** [codetriage/codetriage#456]
It would be nice if we could filter the list on the main page by multiple languages instead of one. Would this make sense as a feature?

**Comment by schneems** [comment]
It might be confusing to people if they select "ruby" then they say, i want to see the "elixir" repos instead, they click on "elixir" and nothing changes because there are more Ruby repois, i.e. they didn't realize you would have to unselect a lang first.

**Comment by prathamesh-sonpatki** [comment]
I agree with @schneems here. Thanks @vishalkuo for the proposal!
