### ISSUE TITLE
Repositories that end in .js are rendered without styles

### ISSUE THREAD

**Issue by locks** [codetriage/codetriage#470]
## Reproduction

* Visit a repository with .js ending:
  * http://www.codetriage.com/emberjs/ember.js
  * http://www.codetriage.com/kangax/fabric.js
  * http://www.codetriage.com/mrdoob/three.js

## Expectation

To see a page rendered properly.

## Observed

Page is rendered without styles.

![fabric.js page on Code Triage without styles](https://cloud.githubusercontent.com/assets/32344/15780354/2e79ac88-2999-11e6-828e-f9b58e381a23.png)

## Notes

As far as I could tell, there were no significant errors in the Console and Network tabs of the developer tools.

**Comment by schneems** [comment]
UGHHHH, thanks. I feel like this is a bug i have to fix every time we upgrade rails. I have a PR to force this to be html
