### ISSUE TITLE
Number of issues is wrong

### ISSUE THREAD

**Issue by ash106** [codetriage/codetriage#471]
I got on CodeTriage yesterday and the number of open issues on CodeTriage and GitHub matched. Now I see something like this:
<img width="347" alt="screen shot 2016-06-03 at 9 49 38 pm" src="https://cloud.githubusercontent.com/assets/3224433/15797191/89687958-29d5-11e6-920c-bbcdcf7529d6.png">
This shows Rails only having 131 open issues when there are 440 open issues when I go to the repo. Am I doing something wrong here?

**Comment by schneems** [comment]
I'll need to investigate

**Comment by schneems** [comment]
Messed up when I renamed a method in a really large commit. I re-enqueued issues they should be fixed within the next hour or so
