### ISSUE TITLE
Counts on Issues on Code Triage and Github Repo don't much

### ISSUE THREAD

**Issue by iamarmanjon** [codetriage/codetriage#474]
This is on the front page.

<img width="1231" alt="screen shot 2016-06-07 at 9 03 20 am" src="https://cloud.githubusercontent.com/assets/7567758/15842847/3d271506-2c8f-11e6-9b74-03d4f9705316.png">

But when you look at the separate repo on github.

<img width="537" alt="screen shot 2016-06-07 at 9 03 53 am" src="https://cloud.githubusercontent.com/assets/7567758/15842856/54fe13f0-2c8f-11e6-8d57-71edff991651.png">
<img width="598" alt="screen shot 2016-06-07 at 9 04 32 am" src="https://cloud.githubusercontent.com/assets/7567758/15842855/54fb7f64-2c8f-11e6-8bc7-dc75129d7b8b.png">
<img width="530" alt="screen shot 2016-06-07 at 9 04 44 am" src="https://cloud.githubusercontent.com/assets/7567758/15842857/5502ec68-2c8f-11e6-8d66-22350d58bf45.png">

Although TravisCI has the same count. Is the count being refreshed every 24 hours? I'm not sure if it's a bug.

**Comment by schneems** [comment]
Count is PRs plus issues. Also we only sync once a day
