### ISSUE TITLE
Rails docs url broken in email

### ISSUE THREAD

**Issue by anilmaurya** [codetriage/codetriage#480]
## I got following content in email:
![screen shot 2016-06-20 at 12 08 51 pm](https://cloud.githubusercontent.com/assets/1912864/16185250/0de3444e-36e0-11e6-8d98-95fa47498678.png)

## When I clicked on link, I got something went wrong.
![screen shot 2016-06-20 at 12 09 05 pm](https://cloud.githubusercontent.com/assets/1912864/16185251/0de3af06-36e0-11e6-9598-7583d3c0b588.png)

**Comment by schneems** [comment]
Here's the rollbar https://rollbar.com/issuetriage/issuetriage/items/31/occurrences/14051094994/

Fixed in a PR.
