### ISSUE TITLE
`foreman start` not working for local setup

### ISSUE THREAD

**Issue by anilmaurya** [codetriage/codetriage#485]
I cloned codetriage repo, and followed setup guide in Readme, however when I run `foreman start` I see strange behaviour. All process exit with code 0.

Log trace:
```
codetriage (master)*$ foreman start
19:36:57 web.1     | started with pid 16419
19:36:57 worker.1  | started with pid 16420
19:36:57 release.1 | started with pid 16421
19:36:58 web.1     | [16419] Puma starting in cluster mode...
19:36:58 web.1     | [16419] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
19:36:58 web.1     | [16419] * Min threads: 5, max threads: 5
19:36:58 web.1     | [16419] * Environment: development
19:36:58 web.1     | [16419] * Process workers: 2
19:36:58 web.1     | [16419] * Preloading application
19:37:08 web.1     | I, [2016-06-23T19:37:08.250196 #16419]  INFO -- : Loaded Configuration: /.../codetriage/config/scout_apm.yml. Using environment: development
19:37:08 worker.1  | I, [2016-06-23T19:37:08.251766 #16420]  INFO -- : Loaded Configuration: /.../codetriage/config/scout_apm.yml. Using environment: development
19:37:08 release.1 | I, [2016-06-23T19:37:08.250200 #16421]  INFO -- : Loaded Configuration: /.../codetriage/config/scout_apm.yml. Using environment: development
19:37:09 web.1     | [16419] * Listening on tcp://0.0.0.0:3000
19:37:09 web.1     | [16419] Use Ctrl-C to stop
19:37:09 web.1     | [16419] - Worker 1 (pid: 16430) booted, phase: 0
19:37:09 web.1     | [16419] - Worker 0 (pid: 16429) booted, phase: 0
19:37:10 release.1 | exited with code 0
19:37:10 system    | sending SIGTERM to all processes
19:37:10 web.1     | [16419] - Gracefully shutting down workers...
19:37:10 worker.1  | terminated by SIGTERM
19:37:10 web.1     | [16419] === puma shutdown: 2016-06-23 19:37:10 +0530 ===
19:37:10 web.1     | [16419] - Goodbye!
19:37:10 web.1     | exited with code 0
```
When I run each process in separate console, its working fine.

**Comment by tejasbubane** [comment]
This is because `release` (which runs `db:migrate`) is exiting. 

Removing the [`release` line from Procfile](https://github.com/codetriage/codetriage/blob/master/Procfile#L3) fixed the issue for me. It was introduced in 856effe57b33dc37409eef43ca13b212be9c3ef5.

**Comment by anilmaurya** [comment]
@tejasbubane Thanks, your solution works for me. 👍

**Comment by prathamesh-sonpatki** [comment]
Can we check for Rails.env and skip release for development?

**Comment by schneems** [comment]
I'll raise this internally at Heroku

**Comment by schneems** [comment]
Works with `$ heroku local`. We should switch docs to use that instead.

**Comment by bluedreamR** [comment]
I installed foreman gem on my react-rails project.
and I setup Procfile.
But foreman command is not working.
Please see below error message.
```
food-demo$ foreman start -p 3000
23:55:31 web.1  | started with pid 78730
23:55:31 api.1  | started with pid 78731
23:55:32 web.1  | npm ERR! Darwin 15.6.0
23:55:32 web.1  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
23:55:32 web.1  | npm ERR! node v7.10.0
23:55:32 web.1  | npm ERR! npm  v4.2.0
23:55:32 web.1  | npm ERR! path /Volumes/Working/React/food-demo/package.json
23:55:32 web.1  | npm ERR! code ENOENT
23:55:32 web.1  | npm ERR! errno -2
23:55:32 web.1  | npm ERR! syscall open
23:55:32 web.1  |
23:55:32 web.1  | npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/Working/React/food-demo/package.json'
23:55:32 web.1  | npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/Working/React/food-demo/package.json'
23:55:32 web.1  | npm ERR! enoent This is most likely not a problem with npm itself
23:55:32 web.1  | npm ERR! enoent and is related to npm not being able to find a file.
23:55:32 web.1  | npm ERR! enoent
23:55:32 web.1  |
23:55:32 web.1  | npm ERR! Please include the following file with any support request:
23:55:32 web.1  | npm ERR!     /Users/liuzheng/.npm/_logs/2017-09-12T15_55_32_040Z-debug.log
23:55:32 web.1  | exited with code 254
23:55:32 system | sending SIGTERM to all processes
23:55:32 api.1  | terminated by SIGTERM
```

**Comment by schneems** [comment]
Works with `$ heroku local`. We should switch docs to use that instead.

**Comment by EduardoRicSan** [comment]
I got the next issue:
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/process.rb:55:in `spawn': Exec format error - bin/webpack-dev-server (Errno::ENOEXEC)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/process.rb:55:in `block in run'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/process.rb:54:in `chdir'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/process.rb:54:in `run'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:356:in `block (2 levels) in spawn_processes'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:353:in `upto'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:353:in `block in spawn_processes'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:352:in `each'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:352:in `spawn_processes'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/engine.rb:57:in `start'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/lib/foreman/cli.rb:42:in `start'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/foreman-0.64.0/bin/foreman:7:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/bin/foreman:22:in `load'
        from C:/RailsInstaller/Ruby2.3.3/bin/foreman:22:in `<main>'

PLEASE HELP ME GUYS!!!!

**Comment by schneems** [comment]
Is this with foreman or Heroku local? Windows doesn’t support processes.

**Comment by EduardoRicSan** [comment]
@schneems is with foreman
