### ISSUE TITLE
Not getting emails from subscribed repos

### ISSUE THREAD

**Issue by gajewsky** [codetriage/codetriage#493]
Hey, I signed up to CodeTriage with my github account, checked language which I am interested in and also subscribed two repos and never got any mails with issues. I double checked all my github connected emails plus the spam. What can possibly cause this?

**Comment by schneems** [comment]
If you go to your users page (click your icon when logged in) you should see your email. Make sure it's correct. I also sent you an email manually from my personal account. Make sure you got it.

**Comment by gajewsky** [comment]
Mailing list works, I managed to find mails from CodeTriage in spam folder. The issue can be closed. Sorry for bothering you and big thanks for help.
