### ISSUE TITLE
Email frequency select box background

### ISSUE THREAD

**Issue by gizotti** [codetriage/codetriage#494]
Currently the Email Frequency select box has a white background, what makes it look like it has no text select.
It also looks very different in Firefox than it does in Safari and Chrome. I couldn't check IE, but if anyone can do that would be awesome.

Here's how they look at the moment:

Safari:
![image](https://cloud.githubusercontent.com/assets/1103597/16913321/d86e6150-4d2c-11e6-9ace-542a6f748d68.png) ![image](https://cloud.githubusercontent.com/assets/1103597/16913272/9012a2fe-4d2c-11e6-84d1-b8e15212fbab.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/1103597/16913285/a2262d6c-4d2c-11e6-9214-b3869649da91.png) ![image](https://cloud.githubusercontent.com/assets/1103597/16913289/a836650a-4d2c-11e6-9864-095f451a2bbe.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/1103597/16913297/b7c6ddba-4d2c-11e6-96a3-c89caac878f0.png) ![image](https://cloud.githubusercontent.com/assets/1103597/16913303/bf03acac-4d2c-11e6-9800-4c1724bc0571.png)

It's a pretty simple one. If you confirm what the layout should be I can get that done.

**Comment by schneems** [comment]
Guess we should default to "daily". Text should be black. A PR would be wonderful

**Comment by gizotti** [comment]
How about the styling of the firefox select? Should I change I make it smaller and make it looks similar to the others?
