### ISSUE TITLE
Display Stars of Repository.

### ISSUE THREAD

**Issue by SagareGanesh** [codetriage/codetriage#502]
It would be nice if we could display the stars of repository on the main page. It will be helpful to know the reputation of repository. Would this make sense as a feature?

What do you think guys? I can create a PR, just let me know.

**Comment by prathamesh-sonpatki** [comment]
Good idea, please create PR

**Comment by SagareGanesh** [comment]
@prathamesh-sonpatki thanks

**Comment by SagareGanesh** [comment]
Hi @prathamesh-sonpatki, I have created [PR](https://github.com/codetriage/codetriage/pull/504) for same, please see it.  In which I have added `stars_count` field in **_Repo_** Model which is set to default 0. For updating existing Repos `stars_count` we need a rake task.  can I  create seperate PR for that? let me know.
thanks.

**Comment by prathamesh-sonpatki** [comment]
Closing in favor of #504
