### ISSUE TITLE
Incorrect issues count.

### ISSUE THREAD

**Issue by amoludage** [codetriage/codetriage#503]
Hi, 
   I found that there are repositories which are showing incorrect **_Issues_** count on dashboard. 

See the [Salt repo](https://github.com/saltstack/salt/issues) which has different issues count.

& See the **Salt** repo's issues count from below screenshot.

![salt-repo](https://cloud.githubusercontent.com/assets/10542896/18009155/b767877e-6bc8-11e6-841c-8fdb120d3fba.png)

 I think the issues count should be updated.

Thoughts please

Thanks.

**Comment by schneems** [comment]
issue count is issues + pull requests. it's also only updated once a day and the main view is cached. It's close enough. If it starts to get off by hundreds then maybe something in the sync task is failing and we need to look at it. Thanks for the issue, this is pretty normal behavior for now.

**Comment by amoludage** [comment]
Hi @schneems 

Thanks for the response. As you said **issue count is issues + pull requests** this is true for most of the repo's but I found one [repo](https://github.com/saltstack/salt/issues) which has issue count which does not match with this logic.

See the **Salt** repo's issue count on dashboard which does not match with issues count + pull request count.

Thanks.
