### ISSUE TITLE
Add search-box to select a language.

### ISSUE THREAD

**Issue by SwatiJadhav46** [codetriage/codetriage#508]
We don't have any search option for required language. It will be better to have search-box here.
![codetraiage](https://cloud.githubusercontent.com/assets/16590944/18838285/8d3027d0-8424-11e6-9754-555691a43a66.png)

I can create a PR for it. Just let me know.

**Comment by prathamesh-sonpatki** [comment]
Why do we need a search box if we already have a "Filter by language" dropdown?

**Comment by SwatiJadhav46** [comment]
I am talking about search feature for list of languages.

**Comment by prathamesh-sonpatki** [comment]
Sorry but I don't understand it. Can you please show a screenshot of what you are suggesting?

Thanks.

**Comment by SwatiJadhav46** [comment]
Right now we show the entire list of languages to user. Please refer the image I have uploaded in first comment. We have drop-down-list with all languages. Instead we can add search tool, to search within language list. It will be easier to user to search for a language.

**Comment by prathamesh-sonpatki** [comment]
I personally think what we have currently is better as user can see all languages and select the one.

@schneems thoughts?

**Comment by SagareGanesh** [comment]
@SwatiJadhav46 good idea. @prathamesh-sonpatki Currently we have 53 languages in our system. 
But as languages increase it will be difficult to search language. so it will be better to have select list with search box. like  
![select_serch_box](https://cloud.githubusercontent.com/assets/16730632/18862182/f6796278-84a7-11e6-879e-e1c0a578ec66.png)

**Comment by SagareGanesh** [comment]
@prathamesh-sonpatki  Also it will be better to have a spinner or some message like _**Searching Repos of LanguageName...**_ on language selection. Because in current system when we select language it takes 5 to 8 seconds to display result..
thoughts?

**Comment by prathamesh-sonpatki** [comment]
I am fine with adding a spinner when the repo search is happening in the background as @SagareGanesh suggested. But I don't think we need to have a languages search dropdown as of now. We can consider adding it when we really need it, like having 100s of languages. 

I am giving this is a close, please feel free to send a PR for the spinner, thanks :smile:
