### ISSUE TITLE
add favourite languages option

### ISSUE THREAD

**Issue by arpit1997** [codetriage/codetriage#509]
This is a feature request. There should an option for tagging favourite languages so that it would be easier for a user to look for relevent repositories. There is very high chances that a developer might know only a couple of languages so showing only relevent repos to the user will be very heplful for the user.. from using this website i have some doubt that this is possible or not. So if feasible consider this

**Comment by schneems** [comment]
You can already set favorite languages in your user edit screen. It doesn't do anything though.

**Comment by arpit1997** [comment]
Did not about that. Sorry for the trouble.
