### ISSUE TITLE
Wrong OG data showing when sharing in facebook!

### ISSUE THREAD

**Issue by rubyrider** [codetriage/codetriage#513]
In facebook:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.codetriage.com

```
og:url	https://www.codetriage.com/
og:type	website
og:title	CodeTriage
og:description	Redis is an in-memory database that persists on disk. The data model is key-value, but many different kind of values are supported: Strings, Lists, Sets, Sorted Sets, Hashes
```
![screen shot 2016-11-17 at 12 03 38 am](https://cloud.githubusercontent.com/assets/417169/20359437/00571d24-ac5a-11e6-9a11-2791468f5090.png)

**Comment by schneems** [comment]
Lol. Whoops. Can you send me a PR?

**Comment by rubyrider** [comment]
I will create one tomorrow :)

**Comment by rubyrider** [comment]
Do we have any specific meta information for header? @schneems  can you provide me with the meta information. I can't see here any.

**Comment by rubyrider** [comment]
Added a pull request #514 as a part of this fix.

**Comment by rubyrider** [comment]
@schneems can we close this issue now ?

**Comment by schneems** [comment]
yep, thanks again!
