### ISSUE TITLE
Seeing projects that aren't mine on the submit repo page

### ISSUE THREAD

**Issue by mattjegan** [codetriage/codetriage#531]
After I login a few days after my initial signup, I clicked the submit repo button. On the page there is a component "Your Repos" under which, was another users repos, there was only 1 so I'm not sure if I could have added others if there were more. When querying the user on github, the starred and watched tabs were also from the same user.

Upon submitting a repo via url, I could see my actual repos.

**Comment by schneems** [comment]
Is this still happening? If you log out and log in, still see it? Did you change your username or email on github?

**Comment by mattjegan** [comment]
@schneems Looks good now, not sure what could've caused it as I didn't change any credentials recently.
