### ISSUE TITLE
Controller codes not as per the style guide

### ISSUE THREAD

**Issue by vamsipavanmahesh** [codetriage/codetriage#535]
I have some files which are not indented, or missing some conventions as per the rubocop style guide. Not that the code is not working, but some experienced people who are seeing them for the first time may see it as a bad taste. May I submit PR, by fixing some of those I could? Let me know your opinions, thanks

- Vamsi

**Comment by rubyrider** [comment]
Please create pull request, so the team members can see what you are trying to do!

**Comment by schneems** [comment]
I would say yes, however be gentle. More PRs is better than one giant PR.

**Comment by prathamesh-sonpatki** [comment]
Please feel free to open pull requests 👍
