### ISSUE TITLE
Receiving email in error

### ISSUE THREAD

**Issue by michaelsking1993** [codetriage/codetriage#557]
(Email instructed me to do this!) I received an email about my github account not working, then was able to log into codetriage perfectly fine through my GitHub account

**Comment by schneems** [comment]
My email told you to open up an issue? If your github account became disconnected for some reason all you had to do was to log in again to fix it. Sounds like everything worked correctly?

**Comment by michaelsking1993** [comment]
I agree, I was also confused about needing to open up an issue, my apologies. I probably misunderstood it, but I copied the email below, which from my understanding states that I needed to try to log in and accept any GitHub prompt, and alert with an issue if I thought I was already authorized.

I tried to log in, but I received zero github prompts, just a message saying that I had logged in. Therefore, I deduced that my initial GitHub authorization when I signed up was enough to be considered "re-authorization", hence the lack of any prompts asking me to sign in with github, and therefore I followed the instruction asking to open up an issue.

My apologies if I misunderstood. Maybe this is a subconscious part of my brain acting like a grade school boy flirting with its crush: it felt the desire to make itself a part of code triage, so it wanted to "flirt" with it by "being mean" and opening up an issue.

Hello @michaelsking1993,

Your GitHub token for Code Triage is returning a non-success status. This can happen if you’ve changed authentication credentials for GitHub or if you revoke API access.

"If you intended to revoke access, and don’t want to receive any more Code Triage emails please Delete Your Account.

If you would like to continue receiving CodeTriage emails, please Log in and re-authorize your GitHub token by pressing “sign in” and accepting any GitHub prompts.

If you’ve believe you’ve already re-authorized your account but are still getting this email please open a GitHub Issue and we can look into it."

**Comment by puffnfresh** [comment]
I got the same email, even though everything is working fine.

**Comment by nateberkopec** [comment]
uhh actually I got one too

**Comment by nateberkopec** [comment]
Uhhh, prod showing that only ~10% of users have valid Github auth tokens.

**Comment by nateberkopec** [comment]
[I just touched that update code](https://github.com/codetriage/codetriage/commit/5645afdaf9071c32eed2a7e5085135fd742b55d7#diff-adfe5926ff1fe9262fddb25bcb8b4704) but I don't think I changed anything. Checking users with token: nil in production shows most of them have pretty random updated_at dates, I don't think I reset everyone's stuff.

**Comment by nateberkopec** [comment]
It is actually possible that github was down at the exact time our update task was running:
<img width="347" alt="screen shot 2017-06-01 at 7 32 23 pm" src="https://cloud.githubusercontent.com/assets/845662/26707296/10219a08-4701-11e7-9b2a-096c4d669aeb.png"> which would have reset people's github tokens.

**Comment by nateberkopec** [comment]
Nah that can't be it. Github was down at ~6:30am, the check_user_auth task runs at 6pm (MST)

**Comment by schneems** [comment]
I sent an email to the github developer support. Maybe they have an idea of what happened.

Some ideas on making that task more robust:

- Check to see if the API is experiencing downtime before doing the check. If it's down then skip invalidating tokens.
- Add in a retry to when a token is show to be invalid, to account for any network hiccups.
- Add an "old_token" field and preserve the last token, so we could diagnose or recover from a "mass token extinction event" in the future.
