### ISSUE TITLE
/bin/sh: jemalloc.sh: command not found

### ISSUE THREAD

**Issue by elliotthilaire** [codetriage/codetriage#558]
https://github.com/codetriage/codetriage/commit/dc26e71601a8887d2b9b01d5841453f09238d597 has introduced a minor documentation bug.

README.md says to launch app with `heroku local` but does not mention you need jemalloc installed.

```
➜  codetriage git:(add-email-time-of-day-preference) heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
5:30:47 PM web.1    |  /bin/sh: jemalloc.sh: command not found
5:30:47 PM worker.1 |  /bin/sh: jemalloc.sh: command not found
[DONE] Killing all processes with signal  null
5:30:47 PM worker.1 Exited with exit code 127
5:30:47 PM web.1    Exited with exit code 127
```

README.md should mention jemalloc is needed or specify a different command to launch the dev server. Not sure which is preferred.

**Comment by nateberkopec** [comment]
yeah sorry about that, adding that to test it on production. I think the best way would probably be a "Procfile.development".

**Comment by elliotthilaire** [comment]
Not a problem. It didn't take long to work out. I got around it with `brew install jemalloc`
I can look at creating a PR for Procfile.development later today. But happy for someone to beat me to it.

**Comment by nateberkopec** [comment]
Nice!
