### ISSUE TITLE
Add Kotlin to the list of languages?

### ISSUE THREAD

**Issue by vjames19** [codetriage/codetriage#562]

**Comment by nateberkopec** [comment]
Yes, PRs welcome

**Comment by schneems** [comment]
languages are pulled from repos which are pulled from github.

To add a language add a repo that points to a kotlin language project and as long as github identifies 
it as `kotlin` we'll pick it up. 

Next add that repo to codetriage.com and you're done.

I think we cache that section of the UI so it may take a bit of time to show up after you've added it.
