### ISSUE TITLE
Why is `Repo#path` duplicating `Repo#full_name`?

### ISSUE THREAD

**Issue by DavidRagone** [codetriage/codetriage#587]
[`Repo#path`](https://github.com/codetriage/codetriage/blob/b57ad8fac2fce0e920e3376693b106e8931de76d/app/models/repo.rb#L156) and [`Repo#full_name`](https://github.com/codetriage/codetriage/blob/b57ad8fac2fce0e920e3376693b106e8931de76d/app/models/repo.rb#L229) are identical, at least after the latter is set by a `before_save` callback. Why do these two exist? It was a bit confusing to me that there would be two ways of calling/finding very similar info, and it's not really clear to me why to have `full_name` given that the info for `path` is stored and can be easily referenced.

**Comment by nateberkopec** [comment]
🤷‍♂️ send a PR that makes it make more sense? 😆

**Comment by schneems** [comment]
I think i forgot that `path` existed and so I added `full_name`. I'm pretty sure i've been using `full_name` more in the code, I believe there's an index on it in the DB as well.

We could get rid of `Repo#path`.

**Comment by DavidRagone** [comment]
Cool! I can take a crack at that. I started to do it, but there's a bit of complexity due to `full_name` being available only for persisted objects, while `path` is available for instantiated objects, so I decided to not tackle it in the same refactor as https://github.com/codetriage/codetriage/pull/590
