### ISSUE TITLE
Flaky test in email_rate_limit_test.rb

### ISSUE THREAD

**Issue by DavidRagone** [codetriage/codetriage#588]
[this spec](https://github.com/codetriage/codetriage/blob/b57ad8fac2fce0e920e3376693b106e8931de76d/test/unit/email_rate_limit_test.rb#L18) would maybe ~1/4 of the time fail locally for me. It's not clear to me why, but seems worth looking into.

**Comment by DavidRagone** [comment]
I can't access the heroku pipeline, but this appears to a spec that is failing on master in CI, intermittently (though I can't force rebuilds on Travis either, so I'm not certain on CI either)

**Comment by nateberkopec** [comment]
Heroku CI is borked r/n because of a bug w/postgres 9.3. I asked @schneems to upgrade but he's out-of-pocket r/n. Watch the Travis builds instead.

**Comment by schneems** [comment]
One of the reasons it is failing is due to https://devcenter.heroku.com/articles/heroku-ci#rails-fixtures-and-referential-integrity. What is the bug with 9.3?

**Comment by nateberkopec** [comment]
@schneems IIRC the fix on Rails only works with Postgres 9.4+

**Comment by nateberkopec** [comment]
so it's strictly inaccurate of me to say "bug with postgres 9.3", but you know what I mean now

**Comment by lostapathy** [comment]
I believe #633 resolved the underlying issue and this can be closed?

**Comment by prathamesh-sonpatki** [comment]
:+1:
