### ISSUE TITLE
Issue resource doesn't have commenters defined

### ISSUE THREAD

**Issue by nateberkopec** [codetriage/codetriage#597]
https://sentry.io/share/issue/3137333132372e333136353532313038/

**Comment by nateberkopec** [comment]
cc @DavidRagone

**Comment by schneems** [comment]
I think this is a result of the memoization bug

**Comment by DavidRagone** [comment]
I haven't used sentry before, is there a way to tell frequency (and whether this was resolved by the memoization bug being fixed)?

**Comment by schneems** [comment]
I think this specific issue is fixed, but there are other memoization bugs. Some of the tasks are stuck in infinite loops.

**Comment by DavidRagone** [comment]
Ouch. Quickly glancing through the changes I made, I don't see any other memoization issues - at least no other glaring ones.

How can I help?
