### ISSUE TITLE
codetriage just sent me a list of 473 issues

### ISSUE THREAD

**Issue by remram44** [codetriage/codetriage#600]
I usually get about 7 issues in the daily email (I'm subscribed to 8 repos). Today I got 473, which is definitely a bug. It is also beyond the email size that my client can display.

Message ID: 597fa39697f07_43fee4cf3896c7412d2@74de5ba4-a901-4b76-8ac0-0200b2190f43.mail

**Comment by schneems** [comment]
Wow, that's...bad. 🙊 Thanks for the report!

We had a snafu where we ran out of credits for sendgrid today, it may be related. I'll have to look into it .

**Comment by schneems** [comment]
I'm looking into this now. For the very short term, you can set an email limit on the number of issues to get in one day. Go to https://www.codetriage.com/users/5617 and update the value. You could keep it low 7 or 10.

Actually I might just go ahead and set a default for everyone to 50 issues until I get this sorted out.  #601

**Comment by schneems** [comment]
Think I've mitigated this as well as I can.
