### ISSUE TITLE
Code Triage auth failure

### ISSUE THREAD

**Issue by doomtr666** [codetriage/codetriage#605]
Hi,
I still receive emails about auth failure, even after following the "the logout, login" instructions.
Christophe

**Comment by schneems** [comment]
Sorry for the delay. I'll be able to check into it tomorrow

**Comment by doomtr666** [comment]
I received a code triage mail this morning, so it seems to work now ;)
Thanks anyway !

**Comment by schneems** [comment]
Great. I'm seeing that your account has an active token right now so you should be set. Let me know if you get another email about auth failure.
