### ISSUE TITLE
Add rubocop ?

### ISSUE THREAD

**Issue by benoittgt** [codetriage/codetriage#606]
Hello

Add rubocop to codetriage [has been mentioned on twitter by schneems](https://twitter.com/schneems/status/893488921660858369). As I said I can work on this but need to know before which « cops » we want and also the way you want this to be done.

For the cops what about using the one from rails? https://github.com/rails/rails/blob/master/.rubocop.yml

For the process, I can open a PR for each folder (or an average of 50 offenses fixed)?

Thanks

**Comment by nateberkopec** [comment]
First step is to just add it with `--auto-gen-config` to prevent any regressions further than what we've already got 😆

**Comment by mikegee** [comment]
Since #608 is merged, close this?

**Comment by schneems** [comment]
Yup, thanks
