### ISSUE TITLE
Rubocop offenses prevent Travis from running tests

### ISSUE THREAD

**Issue by elliotthilaire** [codetriage/codetriage#619]
As a contributor I want to see the full test output from Travis even if something fails.

With the current config, a Rubocop failure will cause travis to stop early and not run the test suite.

Sometimes a Rubocop offense will make it into master. When this happens we can't see if PR's pass the test suite on Travis.

I was about to create a PR to remove rubocop out of the default rake task and into the travis.yml.
But then noticed that would be undoing the work of this commit https://github.com/codetriage/codetriage/pull/611/commits/0eeb4333325d3baaee0ca2a892e398ad8e8e6676

I have opened this issue instead because I don't know the context. 

What was the reason for putting rubocop in the default rake task? 
And can it we move it back, or find another way to get the output of both tests and rubocop showing in Travis?

@benoittgt

**Comment by nateberkopec** [comment]
TBH I like this behavior.

It's maintainer's fault (cough cough me cough cough @schneems) if stuff that breaks rubocop gets merged into master, not Rubocop's fault. We can fix the human problem here.

**Comment by schneems** [comment]
Master should be green, if something goes in that makes it not green, we should revert.

**Comment by benoittgt** [comment]
Hello @elliotthilaire 

Sorry for this unpleasant behavior. 

**I saw this behavior on puma and implemented the same here.** 🤷‍♂️ 
At the beginning task were splitted (it will still output one result for travis) but travis was running test, then rubocop in separate task. I don't think it's possible to have two results rubocop and travis output and I don't think we want this. 

If you are again one or few cop from Rubocop feel free to open an issue. 😉

**Comment by elliotthilaire** [comment]
Hello.

I have made an example app with 4 branches and set it up with travis to demonstrate how separating the steps in .travis.yml works.

i.e,
```
script:
  - bundle exec rubocop
  - bin/rails test
```

Please take a moment to look at:
https://travis-ci.org/elliotthilaire/rails-travis-example-app/branches

* tests-pass-rubocop-passes (build pass)
* tests-pass-rubocop-fails  (fails build)
* tests-fail-rubocop-passes (fails build)
* tests-fail-rubocop-fails  (fails build)

If you have a look at the build logs you will see output from both tests and rubocop and the build still fails appropriately. 

e.g. the tests-fail-rubocop-fails case: https://travis-ci.org/elliotthilaire/rails-travis-example-app/builds/266084051

This feature is documented here: https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step

> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result.

> In the example above, if bundle exec rake build returns an exit code of 1, the following command bundle exec rake builddoc is still run, but the build will result in a failure.

> If your first step is to run unit tests, followed by integration tests, you may still want to see if the integration tests succeed when the unit tests fail.

This is the .travis.yml file.
https://github.com/elliotthilaire/rails-travis-example-app/blob/master/.travis.yml

I wasn't suggesting we make the build green if it shouldn't be. Instead if the rubocop and tests fail, we can find out in a single build instead of two.

This is especially useful if you decide to add more linters or checks to a project.

I hope that provides some clarity. If you have any questions I'll answer. Otherwise I won't push this any further.

**Comment by benoittgt** [comment]
@elliotthilaire that's what I did at the beginning https://github.com/codetriage/codetriage/pull/608/files

I'm ok with splitting the task on travis. It can even be 
```ruby
script:
  - bundle exec rake test
  - bundle exec rake rubocop
```
