### ISSUE TITLE
Sort languages list vertically instead of horizontally

### ISSUE THREAD

**Issue by IvanFon** [codetriage/codetriage#632]
This is a pretty small user experience thing, but I think it would be better to sort the list of languages vertically instead of horizontally. [This Stack Exchange answer explains why](https://ux.stackexchange.com/questions/17176/alphabetical-lists-horizontal-or-vertical).

TL;DR: it's easier and faster to find stuff when vertically sorted

**Comment by jaccarmac** [comment]
It seems your TL;DR is unintentionally reversed...

**Comment by IvanFon** [comment]
@jaccarmac it is, thanks for pointing that out. I’ve edited it.

**Comment by anuj-verma** [comment]
Hi, I agree with @IvanFon point and the answer beautifully explains the point. Is anyone working on this ? If we need this I can send a PR for this.
@prathamesh-sonpatki @schneems

**Comment by prathamesh-sonpatki** [comment]
Sure go ahead and send the PR 👍
