### ISSUE TITLE
Descriptions fail to render markdown including emoji s

### ISSUE THREAD

**Issue by joshunger** [codetriage/codetriage#667]
1. Modify the description of a repo to include an emoji such as `:boom:`
2. Add to code triage

EXPECTING: `:boom:` is rendered correctly
ACTUAL: displays the text `:boom:`

![image](https://user-images.githubusercontent.com/2301847/34408948-0d412a42-eb84-11e7-9f56-726353348408.png)

**Comment by schneems** [comment]
Thanks for the report. We pull that value straight from GitHub’s API. This is a bug on their end. They should serve the emoji instead of the text equivalent.

**Comment by joshunger** [comment]
@schneems did you email support@github.com to report it?

**Comment by schneems** [comment]
I just had a baby. Can you send them an email please?

**Comment by joshunger** [comment]
🍾 👶 !  Sent them an email.
