### ISSUE TITLE
No obvious way to mark a repo dead

### ISSUE THREAD

**Issue by Fake51** [codetriage/codetriage#687]
The codetriage email was trying to push the following repo on me:
https://www.codetriage.com/vayleryn/vayleryncombat

That doesnt exist though - its a 404 on github.

I can't see any obvious way to report the repo as broken or dead. So now you get an issue on github instead

**Comment by schneems** [comment]
This is the way. Thanks for the report. I’ll check when I get back to a computer

**Comment by schneems** [comment]
Deleted. Let me know if you find any others that are dead.
