### ISSUE TITLE
Git branch name is invalid

### ISSUE THREAD

**Issue by bradarv90** [codetriage/codetriage#688]
I just worked on a documentation fix where it suggested my branch name have a `?` in it. This character isn't valid for git branches. The suggested branch name should probably filter out invalid characters. 

Other than that, I truly love this site!

**Comment by schneems** [comment]
Thanks for the feedback do you have a link to the doc method  page by chance?

**Comment by mattzollinhofer** [comment]
Here's the git doc that details valid git branch names: https://git-scm.com/docs/git-check-ref-format 

Point number 5 says no `?`s among other things. [The code](https://github.com/codetriage/codetriage/blob/master/app/controllers/doc_methods_controller.rb#L10) has a link to [this stackoverflow entry](url) describing some approaches. I'd agree with [this comment](https://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name#comment76907451_3651867) basically saying to keep it simple. Only allow numbers, letters, and maybe a couple exceptions. 

Thoughts? I can work up a PR in the next few days to show what I'm thinking.
