### ISSUE TITLE
There should be a warning when user didn't enable JavaScript

### ISSUE THREAD

**Issue by BinotaLIU** [codetriage/codetriage#707]
I am using NoScript plugin, it seems fine with CodeTriage at first.
But when I'm tring to subscribe/unsubscribe a repo, it show me a 404 page. Let me confused. Then I realized that I havn't enable javascript for it.

I think it is better to show user a warning if they didn't enable JavaScript.

**Comment by schneems** [comment]
How do we detect that?

**Comment by BinotaLIU** [comment]
Use ［<noscript>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) element.

**Comment by schneems** [comment]
Great idea. I would love a patch for that.

**Comment by mattzollinhofer** [comment]
I think this issue can be closed now based on #732 right?
