### ISSUE TITLE
Repo was removed

### ISSUE THREAD

**Issue by rlgreen91** [codetriage/codetriage#708]
I just checked CodeTriage, and I noted that our repo, EBWiki, is no longer listed as a project.  Is there a particular reason it was removed?

**Comment by schneems** [comment]
I don't keep logs of when repos are removed. Were you still subscribed to it? Occasionally I will go through and remove repos that have zero subscribers. That's the only time they get removed. You can add it back again here https://www.codetriage.com/repos/new

**Comment by itpwang** [comment]
@rlgreen91 is this still needed?

**Comment by rlgreen91** [comment]
No, not for this.
