### ISSUE TITLE
Add dart in the language dropdown

### ISSUE THREAD

**Issue by AlexiCoard** [codetriage/codetriage#709]
On https://www.codetriage.com/ we have a dropdown to filter project by language.

Unfortunately dart language is missing. As it is gaining popularity with many projects (such as flutter). It could be a good idea to add this language to filters

**Comment by schneems** [comment]
That list is generated programmatically from the projects added to CodeTriage. If it’s not on the list, add a dart project and sign up to triage it. We get our language classification from GitHub.
