### ISSUE TITLE
Repo doesn't exists any more

### ISSUE THREAD

**Issue by mzfr** [codetriage/codetriage#712]
On [page 6](https://www.codetriage.com/?language=Python&page=6) the last repo i.e congredi [https://www.codetriage.com/thetoxicarcade/congredi] doesn't exists any more.

**Comment by schneems** [comment]
When I go to https://www.codetriage.com/thetoxicarcade/congredi it shows up just fine

**Comment by schneems** [comment]
Ahh, you mean it was removed on github. I went ahead and deleted the page on CodeTriage.

**Comment by mzfr** [comment]
yes thats what I meant. Thank you
