### ISSUE TITLE
please how to contribute to CodeTriage

### ISSUE THREAD

**Issue by techsau** [codetriage/codetriage#718]
hello,
please I do not have experience with Github
1- how to fix bugs through codetriage without knowing Github? which tips I should follow if I do not know github?
2- how can I know if there is still bugs on the project? or it is completely fixed?

and many thanks in advance

**Comment by mattzollinhofer** [comment]
@techsau here’s a couple of thoughts about your questions. 

1) code triage is based on using github so to get involved it’s probably best to spend a little time getting familiar with it. The good news is that github is pretty easy to use and there’s a ton of great tutorials! Here’s a few resources to get you started:
    * creating a pull request: 
https://help.github.com/articles/creating-a-pull-request/
    * general github tutorial: https://guides.github.com/activities/hello-world/

2) go to any projects and open the “issues” link. That’s where github keeps track of bugs and work that needs to be done. 

I hope this helps you get started!
