### ISSUE TITLE
Feature Request: Button to jump straight to a new issue

### ISSUE THREAD

**Issue by ZainRizvi** [codetriage/CodeTriage#789]
On a project in CodeTraige, when you click "Triage Issues" you're taken to a page where you can select your email frequency and it has a button saying "Send Me a New Issue!"

That button adds some unnecessary friction since I want to jump straight to a new issue, not have to go check my email first.

Suggestion: Replace that button with "Go Fix An Issue!", which will take you directly to the github page for a new issue for people to look at

**Comment by schneems** [comment]
I'm for it. We will likely need some kind of rate limit so that you can't just click the button a million times. 

Also a page to see your previously subscribed issues would be good too.

**Comment by goronfreeman** [comment]
I just started tackling this one. Hoping to have a PR up in the next couple days.
