### ISSUE TITLE
Code coverage badge

### ISSUE THREAD

**Issue by jhsu802701** [codetriage/codetriage#822]
A code coverage badge would make it easy for any contributor to see which parts of the test suite need the most coverage improvement.

**Comment by schneems** [comment]
I'm not sure I love test PRs that serve only to increase code coverage for code coverage sake.

I'll be fine with a generic "code coverage" badge, but would like to stay away from "50% coverage" etc.

**Comment by schneems** [comment]
If someone wants to send a PR that's fine, but it's not such a high priority that we need to keep the issue open indefinitely.
