### ISSUE TITLE
Remove heroku/heroku and replace with heroku/cli

### ISSUE THREAD

**Issue by stevendaniels** [codetriage/codetriage#824]
The heroku/heroku repo has been archived. We should replace it with the new repo which is at https://github.com/heroku/cli.

**Comment by yvesgurcan** [comment]
I've used the "Submit Repo" functionality on the codetriage.com UI. The repo `heroku/cli` is available here now: https://www.codetriage.com/heroku/cli. However, `heroku/heroku` is still visible at https://www.codetriage.com/heroku/heroku. There isn't a way for users to delete repositories from CodeTriage, so maybe someone with the right permissions can do it?

**Comment by schneems** [comment]
I've not gotten around to adding any house keeping functionality to the UI. I have to do these manually in the console:

```
old_repo.repo_subscriptions.each do |s|
  new_repo.repo_subscriptions.create!(user_id: s.user_id, email_limit: s.email_limit, write: s.write, read: s.read, write_limit: s.write_limit, read_limit: s.read_limit)
rescue => e
  puts "=" * 80
  puts s.id
  puts e
end
```

Users should be moved over and the old `heroku/heroku` destroyed.

**Comment by schneems** [comment]
As a note here's how to delete a repo

```
repo.repo_subscriptions.destroy_all
repo.doc_methods.destroy_all
repo.destroy
```

If you just do a plain `repo.destroy` it has `dependent: destroy` on it, but it can get into weird states.

**Comment by yvesgurcan** [comment]
Cool! I'm glad we could clean this up :)
