### ISSUE TITLE
phantomjs now requires brew cask install

### ISSUE THREAD

**Issue by chemturion** [codetriage/codetriage#852]
Per the README, I ran `brew install redis phantomjs memcached` and got the following error:

```
Error: No available formula with the name "phantomjs" 
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install phantomjs
```

I'm going to create a pull request with the new command for installing `phantomjs`. Is it customary for a pull request to be opened sans issue? I guess that's part of the whole "learning how to contribute" rigamarole (which is why I'm here).

**Comment by gundalow** [comment]
Hi,
Looks like you are trying to push to this repo, rather than your fork, have a look at the following guides: 
* https://guides.github.com/activities/forking/
* https://help.github.com/articles/creating-a-pull-request-from-a-fork/
