### ISSUE TITLE
Replace ruby-sass (deprecated)

### ISSUE THREAD

**Issue by jhsu802701** [codetriage/codetriage#859]
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.           
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install                    
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the 
  sassc gem: https://github.com/sass/sassc-ruby#readme                          
* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

**Comment by lucianosousa** [comment]
it's a easy PR if you are reading this and wants to do your first open source contribution! :D

**Comment by bruno-b-martins** [comment]
I've looked into the `Gemfile` in `master` and we already have:

```
gem 'sassc'
gem 'sassc-rails'
```

So, close this issue?!

**Comment by jhsu802701** [comment]
I am closing this issue because it has been addressed.
