### ISSUE TITLE
Skylight

### ISSUE THREAD

**Issue by jhsu802701** [codetriage/codetriage#871]
When I execute commands like "rails db:migrate", I get the following warning message:
```
WARN -- Skylight: [SKYLIGHT] [3.1.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
```
Is this something I should be concerned about?  Or should I disable this message?

Also, why doesn't this warning appear in the Travis environment?  I did a search of the source code, and the word "skylight" appears only in Gemfile, Gemfile.lock, and README.md (as part of a badge).

**Comment by siaw23** [comment]
> Is this something I should be concerned about?

No.

>Or should I disable this message?

You can, if you want.

**Comment by nateberkopec** [comment]
I think this issue can be closed.
