### ISSUE TITLE
python2 vs python3

### ISSUE THREAD

**Issue by tonitch** [codetriage/CodeTriage#885]
hello,

I'm really hoped by this website and I want to help in python 3 but python2 and python3 are not splited :/

is this an issue from github language detection or is it possible for you to split them ?

(don't know if I need to add info about this issue ?)

ps: I'm french, sorry for any miss-spellings in english ;)

**Comment by Mehonoshin** [comment]
I personally don't think that there is too much difference between 2 and 3 versions of Python.
If we go in this direction then almost every language should be splitted into multiple versions, which is wrong.

**Comment by schneems** [comment]
We don't control the languages, that all comes from github and linguist. If you want the different pythons tagged differently you would have to get them to update it there and we would pick up the change downstream.
