### ISSUE TITLE
No need to include individual fixtures in each test file

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [codetriage/codetriage#939]
We are already loading all fixtures for all tests in test_helper: https://github.com/codetriage/codetriage/blob/8c3495a9651d97b9981a3e3fcf6d0370e193f05c/test/test_helper.rb#L19

So we don't need to include specific fixtures in tests. For eg. https://github.com/codetriage/codetriage/blob/8c3495a9651d97b9981a3e3fcf6d0370e193f05c/test/unit/repo_subscriptions_test.rb#L5 is not needed.

**Comment by NikhilThombare-Cuelogic** [comment]
Thanks for the opportunity @prathamesh-sonpatki  - Removed individual fixtures from other files - https://github.com/codetriage/codetriage/pull/940

**Comment by prathamesh-sonpatki** [comment]
Closed by #940 Thanks!
